# Analytic Programming

> Homework 4: Analytic Programming, NTU, Spring, 2021.

Kuo, Yao-Jen <yaojenkuo@ntu.edu.tw> from [DATAINPOINT](https://www.datainpoint.com)

## Instructions

- We've imported necessary modules/libraries at the beginning of each exercise.
- We've put necessary files(if any) in the working directory of each exercise.
- We've defined the names of functions/inputs/arguments for you.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- Running tests to see if your solutions are right: Kernel -> Restart & Run All -> Restart and Run All Cells.
- You can run tests after each question or after finishing all questions.
- REMEMBER to upload your `.ipynb` file to [CEIBA](https://ceiba.ntu.edu.tw/) before 2021-05-07 20:59:59 when you are done running tests.

In [1]:
import numpy as np
import unittest

## 00. Define a function named `create_nine_one_array` that is able to generate a `(9, 1)` array as specified.

- Expected inputs: None.
- Expected outputs: a (9, 1) array.

```
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
```

In [12]:
def create_nine_one_array():
    """
    >>> nine_one_array = create_nine_one_array()
    >>> nine_one_array.shape
    (9, 1)
    >>> nine_one_array[0, 0]
    1
    >>> nine_one_array[-1, 0]
    9
    """
    ### BEGIN SOLUTION
    arr = np.arange(1,10)
    arr = arr.reshape(9,1)
    return arr
    ### END SOLUTION

## 01. Define a function named `create_one_nine_array` that is able to generate a `(1, 9)` array as specified.

- Expected inputs: None.
- Expected outputs: a (1, 9) array.

```
[[1 2 3 4 5 6 7 8 9]]
```

In [124]:
def create_one_nine_array():
    """
    >>> one_nine_array = create_one_nine_array()
    >>> one_nine_array.shape
    (1, 9)
    >>> one_nine_array[0, 0]
    1
    >>> one_nine_array[0, -1]
    9
    """
    ### BEGIN SOLUTION
    arr = np.array([np.arange(1,10)])
    return arr
    ### END SOLUTION

## 02. Define a function named `create_nine_nine_array` that is able to generate a `(9, 9)` array as specified.

- Expected inputs: None.
- Expected outputs: a (9, 9) array.

```
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
```

In [70]:
def create_nine_nine_array():
    """
    >>> nine_nine_array = create_nine_nine_array()
    >>> nine_nine_array.shape
    (9, 9)
    >>> nine_nine_array[0, 0]
    1
    >>> nine_nine_array[1, 1]
    4
    >>> nine_nine_array[7, 7]
    64
    >>> nine_nine_array[8, 8]
    81
    """
    ### BEGIN SOLUTION
    num = [i*j for i in range(1,10) for j in range(1,10)]
    arr = np.array(num).reshape(9,9)
    return arr
    ### END SOLUTION

## 03. Define a function named `filter_evens` that is able to extract the even numbers from a given array.

- Expected inputs: an array.
- Expected outputs: an array.

In [72]:
def filter_evens(x):
    """
    >>> filter_evens(np.array([5, 5, 6, 6]))
    array([6, 6])
    >>> filter_evens(np.array([1, 2, 3, 4]))
    array([2, 4])
    >>> filter_evens(np.array([0, 1, 2, 3]))
    array([0, 2])
    """
    ### BEGIN SOLUTION
    arr = np.array(x)
    is_even = arr % 2 == 0
    return arr[is_even]
    ### END SOLUTION

## 04. Define a function named `filter_evens_then_product` that is able to product the even numbers from a given array.

- Expected inputs: an array.
- Expected outputs: a numeric.

In [80]:
def filter_evens_then_product(x):
    """
    >>> filter_evens_then_product(np.array([5, 5, 6, 6]))
    36
    >>> filter_evens_then_product(np.array([1, 2, 3, 4]))
    8
    >>> filter_evens_then_product(np.array([0, 1, 2, 3]))
    0
    """
    ### BEGIN SOLUTION
    arr = np.array(x)
    is_even = arr % 2 == 0
    return np.prod(arr[is_even])
    ### END SOLUTION

## 05. Define a function named `find_divisors` that is able to find the divisors of a given integer.

- Expected inputs: an integer.
- Expected outputs: an array.

In [85]:
def find_divisors(x):
    """
    >>> find_divisors(1)
    array([1])
    >>> find_divisors(2)
    array([1, 2])
    >>> find_divisors(3)
    array([1, 3])
    >>> find_divisors(4)
    array([1, 2, 4])
    >>> find_divisors(5)
    array([1, 5])
    """
    ### BEGIN SOLUTION
    divisiors = np.arange(1, x+1)
    is_divisor = x % divisiors == 0
    return divisiors[is_divisor]
    ### END SOLUTION

## 06. Define a function named `var` that is able to calculate the variance of a given array.

PS You may refer to the definition of variance: <https://en.wikipedia.org/wiki/Variance>

\begin{equation}
Var(X) = \frac{1}{n}\sum_{i=1}^{n}(x_i - \mu)^2
\end{equation}

- Expected inputs: an array.
- Expected outputs: a numeric.

In [102]:
def var(X):
    """
    >>> var(np.array([1, 1, 1, 1]))
    0.0
    >>> var(np.array([5, 5, 6, 6]))
    0.25
    >>> var(np.array([5, -5, 6, -6]))
    30.5
    >>> var(np.array([2, 4, 8, 16]))
    28.75
    """
    ### BEGIN SOLUTION
    num = np.array(X)
    return np.square(num - np.mean(num)).sum()/num.shape[0]
    ### END SOLUTION

## 07. Define a function named `cov` that is able to calculate the covariance given 2 same-length arrays.

PS You may refer to the definition of covariance: <https://en.wikipedia.org/wiki/Covariance>

\begin{equation}
cov(X, Y) = \frac{1}{n}\sum_{i=1}^{n}(x_i-\mu_{X})(y_i-\mu_{Y})
\end{equation}

- Expected inputs: 2 arrays.
- Expected outputs: a numeric.

In [109]:
def cov(X, Y):
    """
    >>> X = np.array([1, 1, 1, 1])
    >>> Y = np.array([1, 1, 1, 1])
    >>> cov(X, Y)
    0.0
    >>> X = np.array([5, 5, 6, 6])
    >>> Y = np.array([5, 5, 6, 6])
    >>> cov(X, Y)
    0.25
    >>> X = np.array([5, 5, 6, 6])
    >>> Y = np.array([5, -5, 6, -6])
    >>> cov(X, Y)
    0.0
    """
    ### BEGIN SOLUTION
    return np.sum((X - np.mean(X))*(Y - np.mean(Y)))/X.shape[0]
    ### END SOLUTION

## 08. Define a function named `corr` that is able to calculate the correlation coefficient of 2 same-length arrays.

PS You may refer to the definition of correlation coefficient: <https://en.wikipedia.org/wiki/Pearson_correlation_coefficient>

\begin{equation}
r_{XY} = \frac{cov(X, Y)}{\sqrt{cov(X, X)cov(Y, Y)}}
\end{equation}

- Expected inputs: 2 arrays.
- Expected outputs: a numeric.

In [115]:
def corr(X, Y):
    """
    >>> X = np.array([1, 2])
    >>> Y = np.array([2, 4])
    >>> corr(X, Y)
    1.0
    >>> X = np.array([1, 2])
    >>> Y = np.array([-2, -4])
    >>> corr(X, Y)
    -1.0
    >>> X = np.array([1, 2, 3])
    >>> Y = np.array([2, 4, 6])
    >>> corr(X, Y)
    1.0
    >>> X = np.array([1, 2, 3])
    >>> Y = np.array([-2, -4, -6])
    >>> corr(X, Y)
    -1.0
    """
    ### BEGIN SOLUTION
    return cov(X, Y)/np.sqrt(cov(X, X)*cov(Y, Y))
    ### END SOLUTION

## 09. Define a function named `mse` that is able to calculate the mean squared error given 2 same-length arrays.

PS You may refer to the definition of mean squared error: <https://en.wikipedia.org/wiki/Mean_squared_error>

\begin{equation}
MSE = \frac{1}{n}\sum_{i=1}^{n}(Y_i - \hat{Y_{i}})^2
\end{equation}

- Expected inputs: 2 arrays.
- Expected outputs: a numeric.

In [117]:
def mse(Y, Y_hat):
    """
    >>> Y = np.array([5, 5, 6, 6])
    >>> Y_hat = np.array([5, 5, 6, 6])
    >>> mse(Y, Y_hat)
    0.0
    >>> Y = np.array([5, 5, 6, 6])
    >>> Y_hat = np.array([5, -5, 6, -6])
    >>> mse(Y, Y_hat)
    61.0
    >>> Y = np.array([5, 5, 6, 6])
    >>> Y_hat = np.array([-5, -5, -6, -6])
    >>> mse(Y, Y_hat)
    122.0
    """
    ### BEGIN SOLUTION
    return np.square(Y - Y_hat).sum()/Y.shape[0]
    ### END SOLUTION

## Run tests!

Kernel -> Restart & Run All. -> Restart And Run All Cells.

In [125]:
class TestHomeworkFour(unittest.TestCase):
    def test_00_create_nine_one_array(self):
        nine_one_array = create_nine_one_array()
        self.assertEqual(nine_one_array.shape, (9, 1))
        self.assertEqual(nine_one_array[0, 0], 1)
        self.assertEqual(nine_one_array[-1, 0], 9)
    def test_01_create_one_nine_array(self):
        one_nine_array = create_one_nine_array()
        self.assertEqual(one_nine_array.shape, (1, 9))
        self.assertEqual(one_nine_array[0, 0], 1)
        self.assertEqual(one_nine_array[0, -1], 9)
    def test_02_create_nine_nine_array(self):
        nine_nine_array = create_nine_nine_array()
        self.assertEqual(nine_nine_array.shape, (9, 9))
        self.assertEqual(nine_nine_array[7, 7], 64)
        self.assertEqual(nine_nine_array[7, 8], 72)
        self.assertEqual(nine_nine_array[8, 7], 72)
        self.assertEqual(nine_nine_array[8, 8], 81)
    def test_03_filter_evens(self):
        np.testing.assert_equal(filter_evens(np.array([5, 5, 6, 6])), np.array([6, 6]))
        np.testing.assert_equal(filter_evens(np.array([1, 2, 3, 4])), np.array([2, 4]))
        np.testing.assert_equal(filter_evens(np.array([0, 1, 2, 3])), np.array([0, 2]))
    def test_04_filter_evens_then_product(self):
        self.assertEqual(filter_evens_then_product(np.array([5, 5, 6, 6])), 36)
        self.assertEqual(filter_evens_then_product(np.array([1, 2, 3, 4])), 8)
        self.assertEqual(filter_evens_then_product(np.array([0, 1, 2, 3])), 0)
    def test_05_find_divisors(self):
        np.testing.assert_equal(find_divisors(1), np.array([1]))
        np.testing.assert_equal(find_divisors(2), np.array([1, 2]))
        np.testing.assert_equal(find_divisors(3), np.array([1, 3]))
        np.testing.assert_equal(find_divisors(4), np.array([1, 2, 4]))
        np.testing.assert_equal(find_divisors(5), np.array([1, 5]))
    def test_06_var(self):
        self.assertAlmostEqual(var(np.array([1, 1, 1, 1])), 0.0)
        self.assertAlmostEqual(var(np.array([5, 5, 6, 6])), 0.25)
        self.assertAlmostEqual(var(np.array([5, -5, 6, -6])), 30.5)
        self.assertAlmostEqual(var(np.array([2, 4, 8, 16])), 28.75)
    def test_07_cov(self):
        X = np.array([1, 1, 1, 1])
        Y = np.array([1, 1, 1, 1])
        self.assertAlmostEqual(cov(X, Y), 0.0)
        X = np.array([5, 5, 6, 6])
        Y = np.array([5, 5, 6, 6])
        self.assertAlmostEqual(cov(X, Y), 0.25)
        X = np.array([5, 5, 6, 6])
        Y = np.array([5, -5, 6, -6])
        self.assertAlmostEqual(cov(X, Y), 0.0)
    def test_08_corr(self):
        X = np.array([1, 2])
        Y = np.array([2, 4])
        self.assertAlmostEqual(corr(X, Y), 1.0)
        X = np.array([1, 2])
        Y = np.array([-2, -4])
        self.assertAlmostEqual(corr(X, Y), -1.0)
        X = np.array([1, 2, 3])
        Y = np.array([2, 4, 6])
        self.assertAlmostEqual(corr(X, Y), 1.0)
        X = np.array([1, 2, 3])
        Y = np.array([-2, -4, -6])
        self.assertAlmostEqual(corr(X, Y), -1.0)
    def test_09_mse(self):
        Y = np.array([5, 5, 6, 6])
        Y_hat = np.array([5, 5, 6, 6])
        self.assertAlmostEqual(mse(Y, Y_hat), 0.0)
        Y = np.array([5, 5, 6, 6])
        Y_hat = np.array([5, -5, 6, -6])
        self.assertAlmostEqual(mse(Y, Y_hat), 61.0)
        Y = np.array([5, 5, 6, 6])
        Y_hat = np.array([-5, -5, -6, -6])
        self.assertAlmostEqual(mse(Y, Y_hat), 122.0)

suite = unittest.TestLoader().loadTestsFromTestCase(TestHomeworkFour)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)

test_00_create_nine_one_array (__main__.TestHomeworkFour) ... ok
test_01_create_one_nine_array (__main__.TestHomeworkFour) ... ok
test_02_create_nine_nine_array (__main__.TestHomeworkFour) ... ok
test_03_filter_evens (__main__.TestHomeworkFour) ... ok
test_04_filter_evens_then_product (__main__.TestHomeworkFour) ... ok
test_05_find_divisors (__main__.TestHomeworkFour) ... ok
test_06_var (__main__.TestHomeworkFour) ... ok
test_07_cov (__main__.TestHomeworkFour) ... ok
test_08_corr (__main__.TestHomeworkFour) ... ok
test_09_mse (__main__.TestHomeworkFour) ... ok

----------------------------------------------------------------------
Ran 10 tests in 0.021s

OK


In [126]:
print("You've got {} successes among {} questions.".format(number_of_successes, number_of_test_runs))

You've got 10 successes among 10 questions.
